/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fraudify;

import fraudify.lib.Order;
import fraudify.models.PaymentInfo;
import fraudify.providers.FraudService;
import fraudify.providers.FraudlabsChecker;
import org.junit.Test;

import java.util.HashMap;

import static fraudify.models.PaymentInfo.*;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class FraudifyTest {
    private static final int[] stubNumber = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
    private static final int[] stubCvv = {1, 2, 3};

    @Test
    public void testInternalChecker() {
        Fraudify fraudify = new Fraudify();
        HashMap<String, String> paymentInfoData = new HashMap<>();
        paymentInfoData.put("ip", "127.0.0.1");
        paymentInfoData.put("bill_country", "MX");
        paymentInfoData.put("ship_country", "JP");
        assertEquals(ScreeningResult.HIGH_FRAUD_RISK, fraudify.getScreeningResult(paymentInfoData, stubCvv, stubNumber));

        paymentInfoData.put("bill_country", "US");
        paymentInfoData.put("ship_country", "US");
        assertEquals(ScreeningResult.LOW_FRAUD_RISK, fraudify.getScreeningResult(paymentInfoData, stubCvv, stubNumber));
    }

    @Test
    public void testExternalChecker() {
        FraudService fraudService = mock(FraudService.class);
        Fraudify fraudify = new Fraudify(fraudService);
        when(fraudService.validatePayment(any(PaymentInfo.class))).thenReturn(ScreeningResult.INVALID);
        PaymentInfo paymentInfo = new PaymentInfoBuilder("127.0.0.1").build();
        assertEquals(ScreeningResult.INVALID, fraudify.getScreeningResult(paymentInfo));
        verify(fraudService).validatePayment(paymentInfo);
    }

    @Test
    public void testFraudlabsChecker() {
        Order fraudlabsApi = mock(Order.class);
        FraudService fraudService = new FraudlabsChecker(fraudlabsApi);
        Fraudify fraudify = new Fraudify(fraudService);
        when(fraudlabsApi.feedback(any())).thenReturn("APPROVE");
        PaymentInfo paymentInfo = new PaymentInfoBuilder("127.0.0.1")
                .setShipState("AZ")
                .setShipZipCode("83100")
                .setShipCountry("US")
                .setShipCity("PHX")
                .setShipAddr("Road 1 Long Drive 1234")
                .setPhone("1110001111")
                .setOrderId("asdf-1234-xcvb-2345-xcvb")
                .setNumber(stubNumber)
                .setCvv(stubCvv)
                .setFirstName("John")
                .setLastName("Doe")
                .setEmail("test@email.com")
                .setCurrency("USD")
                .setBillZipCode("83100")
                .setBillState("AZ")
                .setBillCountry("US")
                .setBillCity("PHX")
                .setBillAddr("Road 1 Long Drive 1234")
                .setAmount("1234.34")
                .build();
        assertEquals(ScreeningResult.LOW_FRAUD_RISK, fraudify.getScreeningResult(paymentInfo));
    }
}
